### ISSUE TITLE
Can php version 5.6 be used?

### ISSUE THREAD

**Issue by htf2pc** [zercle/thai-qr-pay#1]
> C:\xampp\htdocs\thai-qr-pay>composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for phpdocumentor/reflection-docblock 3.2.3 -> satisfiable by phpdocumentor/reflection-docblock[3.2.3].
>     - phpdocumentor/reflection-docblock 3.2.3 requires php ^7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
>   Problem 2
>     - Installation request for phpunit/php-token-stream 2.0.1 -> satisfiable by phpunit/php-token-stream[2.0.1].
>     - phpunit/php-token-stream 2.0.1 requires php ^7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
>   Problem 3
>     - phpdocumentor/reflection-docblock 3.2.3 requires php ^7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
>     - phpspec/prophecy v1.7.0 requires phpdocumentor/reflection-docblock ^2.0|^3.0.2 -> satisfiable by phpdocumentor/reflection-docblock[3.2.3].
>     - Installation request for phpspec/prophecy v1.7.0 -> satisfiable by phpspec/prophecy[v1.7.0].

**Comment by bouroo** [comment]
No, because libraries need php 7+
